replicaCount: 1

image:
  repository: ghcr.io/recepgunes1/url-shortener/backend
  tag: "staging-544899c"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  nodePort: null

ingress:
  enabled: true
  host: url-shortener.local

secretName: url-shortener-secrets
