replicaCount: 1

image:
  repository: ghcr.io/recepgunes1/url-shortener/backend
  tag: "staging-18c72cc"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: url-shortener.local

secretName: url-shortener-secrets